export const ALERT_OPEN = "ALERT_OPEN";
export const ALERT_CLOSE = "ALERT_CLOSE";

export const GAME_WINDOW_CLOSE = "GAME_WINDOW_CLOSE";
export const GAME_WINDOW_OPEN_AGENCY = "GAME_WINDOW_OPEN_AGENCY";
export const GAME_WINDOW_OPEN_EMPLOYEES = "GAME_WINDOW_OPEN_EMPLOYEES";
export const GAME_WINDOW_SET_ACTIVE_PAGE = "GAME_WINDOW_SET_ACTIVE_PAGE";

export const MENU_UPDATE = "MENU_UPDATE";

export const STATUS_UPDATE = "STATUS_UPDATE";