export const ALERT = {
	OPEN: "ALERT_OPEN",
	CLOSE: "ALERT_CLOSE"
};

export const GAME = {
	AGENCY: {
		CHANGE_NAME: "GAME_AGENCY_CHANGE_NAME"
	}
}

export const GAME_WINDOW = {
	CLOSE: "GAME_WINDOW_CLOSE",
	OPEN_AGENCY: "GAME_WINDOW_OPEN_AGENCY",
	OPEN_PROJECTS: "GAME_WINDOW_OPEN_PROJECTS",
	OPEN_EMPLOYEES: "GAME_WINDOW_OPEN_EMPLOYEES",
	OPEN_CONFIGURATION: "GAME_WINDOW_OPEN_CONFIGURATION",
	SET_ACTIVE_PAGE: "GAME_WINDOW_SET_ACTIVE_PAGE"
};

export const MENU = {
	UPDATE: "MENU_UPDATE"
};

export const STATUS = {
	UPDATE: "STATUS_UPDATE"
};